/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Регистрация нового пользователя
         * @description Создаёт аккаунт с email + паролем.
         *     Пароль хэшируется перед сохранением.
         *     Возвращает данные пользователя (БЕЗ пароля).
         */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Вход — получить JWT-токен
         * @description OAuth2 password flow. Запрос должен быть application/x-www-form-urlencoded,
         *     НЕ JSON — это стандарт OAuth2, которого требует Swagger UI "Authorize".
         *
         *     Поля формы:
         *     - username = email
         *     - password = пароль
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Данные текущего пользователя
         * @description Возвращает данные залогиненного пользователя.
         *     Требует заголовок Authorization: Bearer <JWT>.
         */
        get: operations["read_me_api_v1_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/variants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список опубликованных вариантов ЕГЭ */
        get: operations["list_variants_api_v1_variants_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/variants/{variant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Вариант целиком со всеми 4 заданиями */
        get: operations["get_variant_api_v1_variants__variant_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Мои записи (по умолчанию все; ?only_paid=true — только платные с AI) */
        get: operations["list_submissions_api_v1_submissions_get"];
        put?: never;
        /**
         * Загрузить запись ответа на задание
         * @description Принимает multipart/form-data:
         *
         *     - **task_id** — UUID задания из варианта.
         *     - **ai_requested** — `true` если пользователь заказал AI-оценку.
         *       Проверяем, что есть `paid_checks_available > 0`, списываем одну.
         *       Запись останется в личном кабинете с результатом AI.
         *     - **ai_requested=false** — бесплатный сценарий.
         *       Пользователь сможет прослушать/скачать файл; через 24ч запись и файл удаляются.
         *     - **audio** — файл (webm/mp3/m4a/mp4/ogg/wav), до 25 МБ.
         *
         *     Файл стримится на диск кусками по 1 МБ, чтобы не грузить весь объём в память.
         */
        post: operations["upload_submission_api_v1_submissions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/submissions/{submission_id}/audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Скачать/прослушать аудио записи */
        get: operations["download_audio_api_v1_submissions__submission_id__audio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/submissions/{submission_id}/evaluation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Получить AI-разбор ответа
         * @description Возвращает разбор (Evaluation) по данному submission.
         *
         *     Статусы HTTP:
         *     - **200** — разбор готов
         *     - **202** — submission ещё в обработке (pending_ai / processing),
         *       фронту надо периодически опрашивать
         *     - **403** — чужой submission
         *     - **404** — submission не существует
         *     - **409** — status=failed (разбор не получится, см. error_message в submission)
         *     - **410** — разбор не заказан (ai_requested=False)
         */
        get: operations["get_evaluation_api_v1_submissions__submission_id__evaluation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Сервер жив?
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root
         * @description Корень — подсказка, где документация.
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/db-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Db Check
         * @description Проверка соединения с PostgreSQL.
         */
        get: operations["db_check_db_check_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_login_api_v1_auth_login_post */
        Body_login_api_v1_auth_login_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /** Password */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /** Client Secret */
            client_secret?: string | null;
        };
        /** Body_upload_submission_api_v1_submissions_post */
        Body_upload_submission_api_v1_submissions_post: {
            /**
             * Task Id
             * Format: uuid
             */
            task_id: string;
            /**
             * Ai Requested
             * @default false
             */
            ai_requested: boolean;
            /**
             * Audio
             * Format: binary
             */
            audio: string;
        };
        /**
         * EvaluationRead
         * @description То, что фронт видит в «Моих тестах» и на странице результата.
         *     raw_ai_response НЕ отдаём наружу — это для внутренней отладки.
         */
        EvaluationRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Submission Id
             * Format: uuid
             */
            submission_id: string;
            /** Transcript */
            transcript: string;
            /** Total Score */
            total_score: number;
            /** Max Score */
            max_score: number;
            /** Criteria Scores */
            criteria_scores: {
                [key: string]: unknown;
            };
            /** Feedback */
            feedback: {
                [key: string]: unknown;
            };
            /** Pronunciation Scores */
            pronunciation_scores: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ExamTaskRead */
        ExamTaskRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Task Number */
            task_number: number;
            task_type: components["schemas"]["TaskType"];
            /** Prompt Text */
            prompt_text: string;
            /** Support Material */
            support_material?: string | null;
            /** Image Url */
            image_url?: string | null;
            /** Image2 Url */
            image2_url?: string | null;
            /** Prep Seconds */
            prep_seconds: number;
            /** Speak Seconds */
            speak_seconds: number;
            /**
             * Variant Id
             * Format: uuid
             */
            variant_id: string;
            /**
             * Interview Audio Urls
             * @description Для Task 3 — список URL'ов к mp3 с озвученными вопросами
             *     (генерируются `scripts/generate_tts.py`). Для остальных типов — [].
             *
             *     URL предсказуемый: /static/tts/variants/<variant_id>/task-<task_id>/q-<N>.mp3.
             *     Отдаём только те, файлы которых реально существуют — если генерацию
             *     не запускали, фронт просто откатится на SpeechSynthesis.
             */
            readonly interview_audio_urls: string[];
        };
        /** ExamVariantRead */
        ExamVariantRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Tasks
             * @default []
             */
            tasks: components["schemas"]["ExamTaskRead"][];
        };
        /** ExamVariantShort */
        ExamVariantShort: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** SubmissionRead */
        SubmissionRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Task Id
             * Format: uuid
             */
            task_id: string;
            task: components["schemas"]["ExamTaskRead"];
            /** Audio Mime Type */
            audio_mime_type: string;
            /** Audio Size Bytes */
            audio_size_bytes: number;
            /** Duration Seconds */
            duration_seconds?: number | null;
            /** Ai Requested */
            ai_requested: boolean;
            status: components["schemas"]["SubmissionStatus"];
            /** Error Message */
            error_message?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * SubmissionStatus
         * @description Жизненный цикл записи:
         *     - uploaded    — файл загружен, AI не требуется (бесплатный сценарий)
         *     - pending_ai  — пользователь заказал AI-проверку, задача в очереди Celery
         *     - processing  — Celery-воркер взял в работу
         *     - evaluated   — AI отработал, результат (Evaluation) сохранён
         *     - failed      — что-то сломалось (логируем и показываем пользователю)
         * @enum {string}
         */
        SubmissionStatus: "uploaded" | "pending_ai" | "processing" | "evaluated" | "failed";
        /**
         * TaskType
         * @description Типы заданий устной части ЕГЭ.
         *     - reading_aloud          — Задание 1: чтение текста вслух (~160 слов).
         *     - compose_questions      — Задание 2: 4 вопроса по объявлению/картинке.
         *     - interview_answers      — Задание 3: ответы на 5 вопросов (интервью).
         *     - photo_based_statement  — Задание 4: высказывание по 2 фото с обоснованием выбора.
         * @enum {string}
         */
        TaskType: "reading_aloud" | "compose_questions" | "interview_answers" | "photo_based_statement";
        /**
         * Token
         * @description Ответ на /auth/login.
         */
        Token: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /**
         * UserCreate
         * @description Тело запроса на регистрацию.
         */
        UserCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Full Name */
            full_name?: string | null;
            /** Password */
            password: string;
        };
        /**
         * UserRead
         * @description То, что мы возвращаем клиенту.
         *     ВАЖНО: здесь нет hashed_password — пароль наружу никогда не уходит.
         */
        UserRead: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Full Name */
            full_name?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Active */
            is_active: boolean;
            /** Is Superuser */
            is_superuser: boolean;
            /** Paid Checks Available */
            paid_checks_available: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_api_v1_auth_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_me_api_v1_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
        };
    };
    list_variants_api_v1_variants_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamVariantShort"][];
                };
            };
        };
    };
    get_variant_api_v1_variants__variant_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                variant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamVariantRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_submissions_api_v1_submissions_get: {
        parameters: {
            query?: {
                /** @description Только платные проверки с AI-результатами */
                only_paid?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_submission_api_v1_submissions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_submission_api_v1_submissions_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_audio_api_v1_submissions__submission_id__audio_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                submission_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evaluation_api_v1_submissions__submission_id__evaluation_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                submission_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    db_check_db_check_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
