"""exam variants tasks submissions

Revision ID: 7a3abc18906c
Revises: d886693abb8b
Create Date: 2026-04-18 00:40:39.317940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a3abc18906c'
down_revision: Union[str, None] = 'd886693abb8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_variants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exam_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('task_number', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.Enum('READING_ALOUD', 'COMPOSE_QUESTIONS', 'INTERVIEW_ANSWERS', 'PHOTO_BASED_STATEMENT', name='tasktype', native_enum=False, length=32), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('support_material', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('image2_url', sa.String(length=512), nullable=True),
    sa.Column('prep_seconds', sa.Integer(), nullable=False),
    sa.Column('speak_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['variant_id'], ['exam_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_tasks_variant_id'), 'exam_tasks', ['variant_id'], unique=False)
    op.create_table('submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('audio_path', sa.String(length=512), nullable=True),
    sa.Column('audio_mime_type', sa.String(length=64), nullable=True),
    sa.Column('audio_size_bytes', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('ai_requested', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'PENDING_AI', 'PROCESSING', 'EVALUATED', 'FAILED', name='submissionstatus', native_enum=False, length=32), nullable=False),
    sa.Column('error_message', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['exam_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissions_task_id'), 'submissions', ['task_id'], unique=False)
    op.create_index(op.f('ix_submissions_user_id'), 'submissions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submissions_user_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_task_id'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_exam_tasks_variant_id'), table_name='exam_tasks')
    op.drop_table('exam_tasks')
    op.drop_table('exam_variants')
    # ### end Alembic commands ###
