"""add evaluations table

Revision ID: 91e4d2704488
Revises: 7a3abc18906c
Create Date: 2026-04-18 21:13:56.141013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '91e4d2704488'
down_revision: Union[str, None] = '7a3abc18906c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('criteria_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('feedback', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pronunciation_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_ai_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cost_usd_cents', sa.Integer(), nullable=True),
    sa.Column('model_version', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluations_submission_id'), 'evaluations', ['submission_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evaluations_submission_id'), table_name='evaluations')
    op.drop_table('evaluations')
    # ### end Alembic commands ###
